### ISSUE TITLE
Another Expr bug? Nope, a Sobel/Prewitt Bug

### ISSUE THREAD

**Issue by theChaosCoder** [vapoursynth/vapoursynth#560]
See https://github.com/HomeOfVapourSynthEvolution/havsfunc/issues/27

The problem starts with the first Expr line here
https://github.com/HomeOfVapourSynthEvolution/havsfunc/blob/7d4a57e93e11d85fbba6f8f92845f00676ff9300/havsfunc.py#L415

**Comment by HolyWu** [comment]
It seems that `Sobel` and `Prewitt` no longer clamp the output pixel to the valid range for bit depth 9~15 when sse2 or avx2 is activated. Is that an intended behavior?

**Comment by sekrit-twc** [comment]
This expression is invalid for a similar reason as #538 , because of an unprotected division by 'y'

havsfunc:

        expr = f'y x - y / {peak} * {scale(lowsens, peak)} - y {scale(256, peak)} + {scale(512, peak)} / {highsens / 100} + *'

Original Didee AVS code:

    so     = mt_lutxy( ugly, are, "x", "y x - y 0.001 + / 255 * "+LOS+" - y 256 + 512 / "+HIS+" + *" )

The 0.001 is there for a reason. As for Sobel/Prewitt, that is indeed a bug.

**Comment by myrsloik** [comment]
Please verify that it's fixed in R50-RC1

**Comment by theChaosCoder** [comment]
I still see differences in Finedehalo with R50


```
co = mvf.Depth(clip, 8).text.Text("orig")
c8 = mvf.Depth(clip, 8)
c10 = mvf.Depth(clip, 10)
c16 = mvf.Depth(clip, 16)
c8=haf.FineDehalo(c8, rx=2.7, darkstr=1 ).text.Text("depth 8")
c10=haf.FineDehalo(c10, rx=2.7, darkstr=1).text.Text("depth 10")
c16=haf.FineDehalo(c16, rx=2.7, darkstr=1).text.Text("depth 16")

clip= core.std.StackHorizontal([co, c8, mvf.Depth(c10, 8), mvf.Depth(c16, 8)])
```
Look at the square
![finedehaloerr](https://user-images.githubusercontent.com/3579830/80389012-dd7d0f80-88aa-11ea-94e3-eecb8085a5ea.JPG)

**Comment by sekrit-twc** [comment]
https://github.com/HomeOfVapourSynthEvolution/havsfunc/issues/27 was closed. Need more info on how to reproduce.

**Comment by theChaosCoder** [comment]
I posted the used frame + script in the linked issue
core.std.SetMaxCPU("none") does not fix it. It only looks a bit different

**Comment by HolyWu** [comment]
Hmm...it's caused by the **_feature_** that `Expr` always clamps output pixel to [0, 65535] for formats use 2 bytes per sample. I wonder why `Expr` wouldn't clamp output pixel to actual valid range for 9~15 bit depth like other filters do. Otherwise script writers just have to put `{max_pixel_value} min` at the end of every possibly affected expression.

**Comment by sekrit-twc** [comment]
What was the original behavior of Expr? I agree that clamping to the valid range is more consistent with the behavior of other filters, but I am hesitant to make semantic changes.

**Comment by myrsloik** [comment]
The original behavior was always clamping to the format range. In VS values outside the specified bitdepth are more or less illegal the way I've written everything else.

**Comment by sekrit-twc** [comment]
Try 1b6c479

**Comment by myrsloik** [comment]
Tell me if you need windows builds

**Comment by theChaosCoder** [comment]
yes please

**Comment by myrsloik** [comment]
https://www.dropbox.com/s/sej0itut1bj2uu3/VapourSynth64-R50-test.exe?dl=1

**Comment by theChaosCoder** [comment]
thx. I can't see any artifacts anymore. Looks good now in dehalo_alpha and finedehalo.

**Comment by myrsloik** [comment]
I guess this is fixed then
