### ISSUE TITLE
Excessive message for failure in plugin autoloading

### ISSUE THREAD

**Issue by YomikoR** [vapoursynth/vapoursynth#899]
Since 0ce561cc215d9fcb230502e3c3faac6ccca28c9a VSEditor reports the following:
No entry point found in xxxxxx\plugins64\libfftw3f-3.dll

**Comment by DJATOM** [comment]
I think those messages should be mtDebug type, that way it wouldn't harm 'production' environments.

**Comment by myrsloik** [comment]
Fixed, warning disabled when loading all plugins

**Comment by YomikoR** [comment]
Users with API3 based previewers still get these messages. Would you show some extra mercy...

**Comment by myrsloik** [comment]
> Users with API3 based previewers still get these messages. Would you show some extra mercy...

Do they implement their own logic to load all plugins in a path? The no entry point warning is disabled when LoadAllPlugins is called

**Comment by YomikoR** [comment]
nvm, was my skill issue
